### ISSUE TITLE
Parcel component used in single-spa app can't grab mountParcel from context

### ISSUE THREAD

**Issue by StyleT** [single-spa/single-spa-react#105]
Hi!
Looks like due to rollup misconfiguration now it's impossible to use Parcel component in apps.

Look at the code in npm package, it lacks some parts of the code that are responsible for the correct work with React Context.

I tried to use esm build with Webpack 4.

Source code in repo:
```
render() {
    if (this.props.appendTo) {
      if (SingleSpaContext && SingleSpaContext.Consumer) {
        return (
          <SingleSpaContext.Consumer>
            {(context) => {
              this.mountParcel = context ? context.mountParcel : null;

              return null;
            }}
          </SingleSpaContext.Consumer>
        );
      } else {
        return null;
      }
    } else {
      const children =
        SingleSpaContext && SingleSpaContext.Consumer ? (
          <SingleSpaContext.Consumer>
            {(context) => {
              this.mountParcel = context ? context.mountParcel : null;

              return null;
            }}
          </SingleSpaContext.Consumer>
        ) : undefined;

      return React.createElement(
        this.props.wrapWith,
        {
          ref: this.handleRef,
          style: this.props.wrapStyle,
          className: this.props.wrapClassName,
        },
        children
      );
    }
  }
```

Builded code (unminified), pay attention to NULL after `this.props.appendTo`:
```
{
        key: "render", value: function () {
            return this.props.appendTo ? null : e.createElement(this.props.wrapWith, {
                ref: this.handleRef,
                style: this.props.wrapStyle,
                className: this.props.wrapClassName
            }, void 0)
        }
    }
```

When I compile library from the source code on my own - it works great.

**Comment by joeldenning** [comment]
Hmm yes I see that in the published file. It seems that this was introduced in https://github.com/single-spa/single-spa-react/pull/102 as part of the 4.0.0 release. Probably related from upgrading rollup from 2.6 to 2.38. I'll look into it.

**Comment by joeldenning** [comment]
After some investigation, I discovered this wasn't related to the rollup upgrade, but rather from switching from `import 'single-spa-react'` to `import './single-spa-react'` inside of parcel.js. This happened in https://github.com/single-spa/single-spa-react/pull/101/files#diff-660ba0e334878cc4c40deb046d413bf056dbde6a35edec191ed23fdc3022cceaR7 and I made the change because packages referencing themselves doesn't work in all envs.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-react/releases/tag/v4.1.1

**Comment by gjhommersom** [comment]
It seems that this is still an issue when using the package. Adding the code directly to the project fixes the issue. It can also be fixed by proving the `mountParcel` function from `single-spa`.

In the minified code in the package I found this block of code:
```
var p = null;
try {
    p = require("react").createContext()
} catch (e) {}
```
This is the replacement of `import { SingleSpaContext } from "./single-spa-react";` and it fails with a `require is not defined` error.

**Comment by joeldenning** [comment]
@gjhommersom could you provide a demonstration of the issue? This could be caused by bundler config.

**Comment by gjhommersom** [comment]
I run `create-single-spa` with:
* app/parcel
* react
* yarn
* typescript

Change the root component to:
```
import React from "react";
import Parcel from 'single-spa-react/parcel'

export default function Root(props) {
  return <section><Parcel config={()=>{return System.import('')}}/></section>;
}
```

And run `yarn start:standalone`.

**Comment by joeldenning** [comment]
I was able to reproduce the problem - turns out that the rollup config still had a mistake even after 4.1.1 which caused parcel.js to bundle single-spa-react.js within it rather than requiring it at runtime. I put together a fix at https://github.com/single-spa/single-spa-react/pull/111

**Comment by joeldenning** [comment]
That fix is published in https://github.com/single-spa/single-spa-react/releases/tag/v4.1.2
