### ISSUE TITLE
Parcel never mounts component with StrictMode enabled

### ISSUE THREAD

**Issue by eljo** [single-spa/single-spa-react#160]
With React 18 development library and <React.StrictMode> the <Parcel> component does not mount the actual parcel. 

Observed flow:
* componentDidMount is called which calls addThingToDo
* componentWillUnmount is called which calls addThingToDo and immediately sets this.unmounted = true
* First addThingToDo is invoked and immediately returns as this.unmounted is true.

**Comment by MilanKovacic** [comment]
Hi, did you solve the problem?

**Comment by webJose** [comment]
I just stumbled upon this same scenario.

**Comment by BournazosHarry** [comment]
We experience the same issue.
We use the Parcel component and what I noticed is that it mounts it, it's visible for a split of a second and then it unmounts it.
Could it be that in the second render of StrictMode the parcel is considered mounted? Some timing issue maybe?
I hope you can figure it out soon.

**Comment by ArsBarsj** [comment]
React 19 is on the way, can anyone tell me when the release with this fix will be?

**Comment by joeldenning** [comment]
Fixed in [6.0.2](https://github.com/single-spa/single-spa-react/releases/tag/v6.0.2)

**Comment by whyssea** [comment]
Hi, I still have this problem after upgrade to 6.0.2. Bundler - Vite
![{88234A02-D622-4989-9B15-6E9CB3835168}](https://github.com/user-attachments/assets/f9db546d-4a50-4a00-b9eb-e888938a35ec)
